### ISSUE TITLE
ClusterWorkspace API bump 

### ISSUE THREAD

**Issue by fgiloux** [openshift-pipelines/pipeline-service#115]
The API version in kcp for ClusterWorkspace has been bumped from `apiVersion: tenancy.kcp.dev/v1alpha1` to `apiVersion: tenancy.kcp.dev/v1beta1`
we make use of this API at least in [pipeline-service-org.yaml](https://github.com/openshift-pipelines/pipelines-service/blob/main/local/kcp/pipelines-service-org.yaml)
As long as we follow release-0.5 we still consume v1alpha1 but when we move to the next release we will need to move to the new API version (there is currently no conversion in place in the main branch).

**Comment by Roming22** [comment]
Is this still relevant? We're on kcp v0.9.0, and I still see the alpha version:
```
> kkcp api-resources
NAME                              SHORTNAMES   APIVERSION                             NAMES
[...]
clusterworkspaces                              tenancy.kcp.dev/v1alpha1               false        ClusterWorkspace
clusterworkspacetypes                          tenancy.kcp.dev/v1alpha1               false        ClusterWorkspaceType
workspaces                        ws           tenancy.kcp.dev/v1beta1                false        Workspace
synctargets                                    workload.kcp.dev/v1alpha1              false        SyncTarget
```

**Comment by Roming22** [comment]
KCP being out of the picture, I'm closing this issue as deprecated.
