### ISSUE TITLE
KCP cluster registration to ArgoCD fails as unauthenticated

### ISSUE THREAD

**Issue by matzew** [openshift-pipelines/pipeline-service#125]
After #124 going with the `release-0.5` plugin, the script ends here:

```
  - KCP cluster registration to ArgoCD: %                           
```

Running with `bash -x` I get some more info:

```
ckcp git:(main) ✗ export KUBECONFIG=merged-config.kubeconfig:/home/matzew/Downloads/cluster-bot-2022-06-28-095651.kubeconfig.txt:/home/matzew/go/src/github.com/openshift-pipelines/pipelines-service/ckcp/work/kubeconfig/admin.kubeconfig
➜  ckcp git:(main) ✗ argocd cluster add workspace.kcp.dev/current --name=kcp --system-namespace default --yes

INFO[0000] ServiceAccount "argocd-manager" already exists in namespace "default" 
INFO[0001] ClusterRole "argocd-manager-role" updated    
INFO[0001] ClusterRoleBinding "argocd-manager-role-binding" updated 
FATA[0003] rpc error: code = Unauthenticated desc = the server has asked for the client to provide credentials 
➜  ckcp git:(main) ✗ 
```

**Comment by bnallapeta** [comment]
@matzew I'm not sure if this is something to do with the export KUBECONFIG command having multiple kubeconfig. I saw @rhuss post a question about this in kcp forum too. 
Could you please try once with a single kubeconfig and let us know the status?

**Comment by xinredhat** [comment]
@matzew I were troubleshooting the issue and were able to reproduce when I used kubeconfig that was generated using ClusterDeployment CR. But with a kubeconfig generated from oc login, you could not see this issue. Can you try the kubeconfig generated from oc login?

**Comment by Roming22** [comment]
@matzew This issue seems to be stale, and we will be closing it as such. Please reach out if the issue is still relevant.

**Comment by Roming22** [comment]
KCP being out of the picture, I'm closing this issue as deprecated.
