### ISSUE TITLE
Workspaces & RBAC

### ISSUE THREAD

**Issue by fgiloux** [openshift-pipelines/pipeline-service#132]
The way workspaces, organizations are structured and the associated RBAC are applied are currently changing in kcp. It is expected that a good amount of these changes: [PR 996](https://github.com/kcp-dev/kcp/pull/996), [bump of ClusterWorkpsace API version](https://github.com/openshift-pipelines/pipelines-service/issues/115) will land in release 0.6.

This is issue is about reviewing our service account creation (used by Pipelines as Code workflows) and right allocation, so that:
- it works well with kcp 0.6
- checks in images/kcp-registrar/register.sh identify whether [a workspace can be reused or need to be created](https://github.com/openshift-pipelines/pipelines-service/pull/130)

**Comment by Roming22** [comment]
KCP being out of the picture, I'm closing this issue as deprecated.
