### ISSUE TITLE
Pipeline as Code and OpenShift 4.11

### ISSUE THREAD

**Issue by fgiloux** [openshift-pipelines/pipeline-service#190]
In the [documentation](https://github.com/openshift-pipelines/pipeline-service/tree/main/gitops#install-and-setup-pipelines-as-code) we guide users to install upstream Pipeline as Code. This is fine but we should mention that it also comes with OpenShift Pipelines. The latest version shipped with 4.11 also supports GitLab integration.

**Comment by Roming22** [comment]
PaC is not a manual install anymore and is installed by our manifests. With the coming upgrade to OpenShift Pipelines 1.9, PaC will be automatically installed by the operator.

I'm closing this issue as I believe it is now stale.
