### ISSUE TITLE
The rights allocated to Argo CD service account are not tight

### ISSUE THREAD

**Issue by xinredhat** [openshift-pipelines/pipeline-service#213]
For now pipeline-service doesn't define the proper rights to  Argo CD service account. It grant all of rights to Argo CD service account, for example [role.yaml](https://github.com/openshift-pipelines/pipeline-service/blob/main/gitops/compute/pac-manager/role.yaml#L6-L16).This is not right.  The rights will need to be tighten.

**Comment by Roming22** [comment]
@ramessesii2 That's an issue you might want to look into as you are reviewing the SA security for the various operators.
