### ISSUE TITLE
script silently swallowing errors

### ISSUE THREAD

**Issue by fgiloux** [openshift-pipelines/pipeline-service#216]
@xinredhat @Roming22 

There are many occurrences in  the ckcp script of things like [this](https://github.com/openshift-pipelines/pipeline-service/blob/main/ckcp/openshift_dev_setup.sh#L159) where the error output is redirected to the standard ouptut, which is sent to /dev/null

We should never do things like that. It makes troubleshooting impossible.

**Comment by xinredhat** [comment]
I totally agree. For now  It's very difficult to debug them when failure happened. Every time I took lot of time to reproduce the failure by removing the output redirection.

**Comment by xinredhat** [comment]
This issue was fixed, we can close it.
