### ISSUE TITLE
Update ckcp

### ISSUE THREAD

**Issue by ramessesii2** [openshift-pipelines/pipeline-service#247]
With more people using `ckcp` to get the gist of Pipeline Service and other purposes, we've more feedback.
It would be nice to have the `ckcp` deployment flow to be -
1. Update `config.yaml`.
2. Apply the configs from `config.yaml` using a different script- `apply_config.sh`, so that a user has to do minimal changes and possibly only to `config.yaml`.
3. Run `Openshift_dev_setup.sh`.

**Comment by Roming22** [comment]
@ramessesii2 Didn't you take care of that in a recent commit? If yes, please reference it here and close the issue.

**Comment by ramessesii2** [comment]
Not really. The intent was to create a `preview state` of `infra-deployments` like feature which will take care of possibly creating a new branch in user's fork, change the parent `argocd.yaml` to refer the user's repo and branch and commit those changes and finally push to their repo as well. This will make sure that the pipeline-service setup on the compute is referencing user's remote git repo (Just to point it out - we never refer a local system's argo app, rather we create compute environment using kustomization which references a remote git repo).
It came out in one of the slack conversations.

**Comment by ramessesii2** [comment]
Closing this issue since it's related to kcp-infra.
