### ISSUE TITLE
Provide flags for openshift_dev_setup.sh to accept kcp_workspace and kcp_organization

### ISSUE THREAD

**Issue by bnallapeta** [openshift-pipelines/pipeline-service#249]
- Currently, both these values are hardcoded in the script (pipeline-service-compute and root:default).
- Would be useful to provide params for users to enter their own kcp workspace and organization.

**Comment by Roming22** [comment]
@bnallapeta Can this issue be closed since #309 has been merged?

**Comment by bnallapeta** [comment]
@Roming22 309 is still open. Waiting for you to process the open comments.

**Comment by Roming22** [comment]
Sorry, I got confused :)

**Comment by ramessesii2** [comment]
This issue is related to kcp-infra. Can we close it now @bnallapeta?

**Comment by Roming22** [comment]
@bnallapeta Closing this issue, as it is stale.
