### ISSUE TITLE
openshift_dev_setup.sh doesn't work on Mac because Podman cannot mount native source folder 

### ISSUE THREAD

**Issue by xinredhat** [openshift-pipelines/pipeline-service#276]
**Description:**
Podman running on Mac is using remote model. By default bind volume will use source folders on podman server's host(here it is a VM running on Mac as pondman server).  When you init Poman machion with command `podman machine init`, the VM doesn't mount the any native source folder to the VM. The result is that when you try to mount the native source folder  with podman command, it reports  `no such file or directory`. Below is the error I am seeing when executing openshift_dev_setup.sh on Mac.

```
podman run --rm --env COSIGN_PASSWORD=Q9HDartEsayOVxRW --volume /var/folders/s0/jr_x9_mj0sb2np74b8427w180000gn/T/tmp.IgGQXBSs/credentials/manifests/compute/tekton-chains/tmp:/workspace:z --workdir /workspace --entrypoint /usr/bin/cosign quay.io/redhat-appstudio/appstudio-utils:eb94f28fe2d7c182f15e659d0fdb66f87b0b3b6b generate-key-pair
        Error: statfs /var/folders/s0/jr_x9_mj0sb2np74b8427w180000gn/T/tmp.IgGQXBSs/credentials/manifests/compute/tekton-chains/tmp: no such file or directory
```

There is a discussion about it  https://github.com/containers/podman/discussions/13537

**Comment by adambkaplan** [comment]
Since this is using a basic `podman run` command, there's no reason why we shouldn't use `CONTAINER_ENGINE` env var so that it can be swapped with docker.

I ran into a similar issue doing development in a toolbox. In that case, I had to modify one of the scripts to use `flatpak-spawn --host podman` as the container engine.

**Comment by Roming22** [comment]
@adambkaplan @xinredhat Please validate that this issue is fixed. Close the issue if your test is successful.

**Comment by xinredhat** [comment]
When using CONTAINER_ENGINE=docker, this issue is gone on Mac
