### ISSUE TITLE
Improve ci by using a pre-built image with required tools

### ISSUE THREAD

**Issue by Mo3m3n** [openshift-pipelines/pipeline-service#421]
Currently we install,at [runtime](https://github.com/openshift-pipelines/pipeline-service/blob/86cc667aeac0f3ab6d3f926f43eb1f4486510f43/.tekton/pipeline-service-test.yaml#L209) (when ci is triggered), the required tools for ci tests.
Which makes CI slow and hard to keep tools versions aligned with the dependencies versions.
Using an image with required tools already installed would make this simpler

**Comment by Roming22** [comment]
@Mo3m3n is that fixed by #427?

**Comment by Mo3m3n** [comment]
yes it is
