### ISSUE TITLE
Figure out the long term solution for storing/using modified images of triggers, pipelines etc

### ISSUE THREAD

**Issue by bnallapeta** [openshift-pipelines/pipeline-service#49]
- Currently, the pipelines and triggers components we have in the repo are modified versions to run with kcp.
- As part of that, we have applied patches, built images and use them where they are required.
  - eg: [triggers pod](https://github.com/openshift-pipelines/pipelines-service/blob/main/gitops/triggers/triggers-controller/base/deployment.yaml) uses quay.io/bnr/eventlistenersink-7ad1faa98cddbcb0c24990303b220bb8](http://quay.io/bnr/eventlistenersink-7ad1faa98cddbcb0c24990303b220bb8 image.
- To not depend on individual dev's quay image, we either 
    - should let every user build and upload the image and dynamically use that in the deployment
    - store the modified image in some generic quay repo.

**Comment by fgiloux** [comment]
quay.io may be preferred but `ghcr.io`could be a quick option. It should be looked at as part of the CI work. argo-cd registration image should then get built and pushed to the desired repo as well.

**Comment by Roming22** [comment]
> quay.io may be preferred but `ghcr.io`could be a quick option. It should be looked at as part of the CI work. argo-cd registration image should then get built and pushed to the desired repo as well.

I agree that `ghcr.io` should be good enough for day 1.

**Comment by fgiloux** [comment]
Currently using ghcr.io. Keeping the issue open for tracking the availability of an org in quay.io and possibly other container registries

**Comment by ramessesii2** [comment]
hey @bnallapeta, I think we have achieved this goal. Shall we close it?

**Comment by bnallapeta** [comment]
@ramessesii2 Yep. We are now storing them in quay.io and may store it in multiple registries in the future. Good to be closed.
