### ISSUE TITLE
ckcp demo workspace not usable

### ISSUE THREAD

**Issue by adambkaplan** [openshift-pipelines/pipeline-service#53]
When deploying the `ckcp` cluster inside CodeReadyContainers, I get the following error when trying to use the "demo" kcp workspace:

```sh
$ kubectl kcp workspace use demo
error: current URL "https://ckcp-ckcp.apps-crc.testing:443" does not point to cluster workspace
```

Dumping the workspace YAML, it appears that the demo workspace is not yet initialized:

```yaml
apiVersion: tenancy.kcp.dev/v1alpha1
kind: Workspace
metadata:
  clusterName: admin
  creationTimestamp: "2022-04-29T18:11:45Z"
  generation: 1
  name: demo
  resourceVersion: "169"
spec:
  inheritFrom: admin
status:
  conditions:
  - lastTransitionTime: "2022-04-29T18:11:45Z"
    message: No shards are available to schedule Workspaces to.
    reason: Unschedulable
    severity: Error
    status: "False"
    type: WorkspaceScheduled
  - lastTransitionTime: "2022-04-29T18:11:45Z"
    message: No connection information on target WorkspaceShard.
    reason: Missing
    severity: Error
    status: "False"
    type: WorkspaceURLValid
  phase: Initializing
```

Is the KubeConfig URL for kcp missing the path to the root workspace? Is there additional configuration needed to get a demo workspace set up?

**Comment by Roming22** [comment]
The ckcp environment setup leaves you in a "fresh" deployment of KCP and pipeline service, with `root` as the only available workspace.
It is up to you to create additional workspaces with `kubectl kcp workspace create my_workspace`.

**Comment by bnallapeta** [comment]
@adambkaplan ckcp has been developed further since this issue is raised. Please confirm if this issue still exists. Else, we could close the issue.

**Comment by Roming22** [comment]
Marking the issue as stale. @adambkaplan Please reach out if the issue should not be closed.

**Comment by Roming22** [comment]
Fixing status.
