### ISSUE TITLE
Kcp-in-a-pod - towards more generic and synchronized manifests

### ISSUE THREAD

**Issue by ramessesii2** [openshift-pipelines/pipeline-service#81]
#### Tasks - 
* Split the ckcp deployment into two applications:
                       - Operator installation through subscription
                       - Next steps as an Application with [presync hook](https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/) waiting for the API to be available (with timeout).
             
predecessor - #68

**Comment by bnallapeta** [comment]
@ramessesii2 Is this issue worked on? I believe the first one is done. Not so sure about the presync hook. Do we need that anymore?

**Comment by ramessesii2** [comment]
Hey @bnallapeta, part of this epic i.e., Operator installation through subscription and deployment through argo cd is done. Presync hook seems good to have for ckcp but not important right now.

**Comment by Roming22** [comment]
KCP being out of the picture, I'm closing this issue as deprecated.
